CREATE TABLE Author (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Book (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    authorId INT NOT NULL,
    FOREIGN KEY (authorId) REFERENCES Author(id)
);

CREATE TABLE Copy (
    id INT PRIMARY KEY AUTO_INCREMENT,
    bookId INT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (bookId) REFERENCES Book(id)
);

CREATE TABLE User (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Loan (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    copyId INT NOT NULL,
    loanDate DATETIME NOT NULL,
    dueDate DATETIME NOT NULL,
    returnDate DATETIME,
    FOREIGN KEY (userId) REFERENCES User(id),
    FOREIGN KEY (copyId) REFERENCES Copy(id)
);